name: qrcodeprint
description: Generate Qrcode

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  printing: ^5.11.0
  pdf: ^3.6.0
  mobile_scanner: ^3.2.0
  image_picker: ^0.8.7+5




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


